import { useState } from 'react';
import { FileDown, Loader2 } from 'lucide-react';

function ExportPDF({ data }) {
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    setExporting(true);
    try {
      const html2pdf = (await import('html2pdf.js')).default;

      const container = document.createElement('div');
      container.style.padding = '40px';
      container.style.fontFamily = 'Inter, system-ui, sans-serif';
      container.style.color = '#1e293b';
      container.style.maxWidth = '800px';

      const section = (title, content) => `
        <div style="margin-bottom:24px;page-break-inside:avoid;">
          <h3 style="font-size:14px;font-weight:700;color:#6366f1;margin-bottom:8px;text-transform:uppercase;letter-spacing:1px;">${title}</h3>
          <div style="background:#f8fafc;border-radius:8px;padding:16px;font-size:13px;line-height:1.7;color:#334155;white-space:pre-wrap;">${content || 'N/A'}</div>
        </div>`;

      const tags = (arr) => arr?.map(t => `<span style="display:inline-block;background:#eef2ff;color:#4f46e5;padding:4px 10px;border-radius:20px;font-size:11px;margin:2px 4px 2px 0;">#${t}</span>`).join('') || '';

      container.innerHTML = `
        <div style="text-align:center;margin-bottom:32px;padding-bottom:20px;border-bottom:2px solid #e2e8f0;">
          <h1 style="font-size:24px;font-weight:800;color:#1e293b;margin:0;">MarketAI Campaign Report</h1>
          <p style="font-size:12px;color:#94a3b8;margin-top:6px;">Generated on ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}</p>
        </div>

        <h2 style="font-size:18px;font-weight:700;color:#1e293b;margin-bottom:16px;">📝 Marketing Content</h2>
        ${section('SEO Web Description', data.seo)}
        ${section('Instagram Caption', data.instagram)}
        ${section('LinkedIn Post', data.linkedin)}
        ${section('Twitter / X Post', data.twitter)}
        ${section('Facebook Post', data.facebook)}
        <div style="margin-bottom:24px;">
          <h3 style="font-size:14px;font-weight:700;color:#6366f1;margin-bottom:8px;text-transform:uppercase;letter-spacing:1px;">Dynamic Tags</h3>
          <div style="padding:8px 0;">${tags(data.tags)}</div>
        </div>

        ${data.adCopy ? `
          <div style="page-break-before:always;"></div>
          <h2 style="font-size:18px;font-weight:700;color:#1e293b;margin-bottom:16px;">📢 Ad Copy</h2>
          ${data.adCopy.google ? `
            ${section('Google Ads - Headlines', data.adCopy.google.headlines?.join('\n'))}
            ${section('Google Ads - Descriptions', data.adCopy.google.descriptions?.join('\n'))}
          ` : ''}
          ${data.adCopy.facebook ? `
            ${section('Facebook Ad - Headline', data.adCopy.facebook.headline)}
            ${section('Facebook Ad - Primary Text', data.adCopy.facebook.primaryText)}
            ${section('Facebook Ad - CTA', data.adCopy.facebook.cta)}
          ` : ''}
          ${data.adCopy.linkedin ? `
            ${section('LinkedIn Ad - Headline', data.adCopy.linkedin.headline)}
            ${section('LinkedIn Ad - Intro', data.adCopy.linkedin.introText)}
          ` : ''}
        ` : ''}

        ${data.emailCopy ? `
          <div style="page-break-before:always;"></div>
          <h2 style="font-size:18px;font-weight:700;color:#1e293b;margin-bottom:16px;">📧 Email Marketing</h2>
          ${['launch', 'promotional', 'followup'].map(key => {
            const e = data.emailCopy[key];
            if (!e) return '';
            return `
              ${section(`${key.charAt(0).toUpperCase() + key.slice(1)} Email - Subject`, e.subject)}
              ${section(`${key.charAt(0).toUpperCase() + key.slice(1)} Email - Body`, e.body)}
            `;
          }).join('')}
        ` : ''}

        <div style="margin-top:40px;padding-top:16px;border-top:1px solid #e2e8f0;text-align:center;">
          <p style="font-size:11px;color:#94a3b8;">Generated by MarketAI — AI-Powered Marketing Platform</p>
        </div>
      `;

      document.body.appendChild(container);

      await html2pdf().set({
        margin: [10, 10],
        filename: `campaign-${Date.now()}.pdf`,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
      }).from(container).save();

      document.body.removeChild(container);
    } catch (err) {
      console.error('PDF export failed:', err);
    } finally {
      setExporting(false);
    }
  };

  return (
    <button onClick={handleExport} disabled={exporting}
      className="btn-secondary flex items-center justify-center gap-2 py-3 flex-1">
      {exporting ? (
        <><Loader2 className="w-4 h-4 animate-spin" /> Exporting...</>
      ) : (
        <><FileDown className="w-4 h-4" /> Export PDF</>
      )}
    </button>
  );
}

export default ExportPDF;
